repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
        - id: check-yaml
          args: [--allow-multiple-documents]
        - id: end-of-file-fixer
        - id: trailing-whitespace
          args: [--markdown-linebreak-ext=md]
        - id: check-case-conflict
        - id: check-added-large-files
        - id: check-executables-have-shebangs
        - id: check-merge-conflict
        - id: check-symlinks
        - id: requirements-txt-fixer

    - repo: https://github.com/psf/black
      rev: 19.10b0
      hooks:
        - id: black

    - repo: https://gitlab.com/pycqa/flake8
      rev: "3.7.9"
      hooks:
        - id: flake8
          args: ["--select=E9,F63,F7,F82, F401"]

    - repo: https://github.com/asottile/seed-isort-config
      rev: v2.2.0
      hooks:
        - id: seed-isort-config

    - repo: https://github.com/timothycrosley/isort
      rev: 5.1.1
      hooks:
        - id: isort
          args: ["--filter-files"]
