version: "3"

services:
  db:
    image: postgres:11
    volumes:
      - local_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  backend:
    stdin_open: true
    tty: true
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /app
    restart: always
    volumes:
      - .:/app:delegated
    env_file:
      - ./secrets.env
    ports:
      - 8000:8000
    depends_on:
      - db

  # comment out when deploying to prod
  frontend:
    build:
      context: .
    command: yarn run start
    working_dir: /app/frontend
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - node_modules:/app/frontend/node_modules
    ports:
      - 3000:3000
    stdin_open: true

volumes:
  local_data:
  node_modules:
