version: "3"

services:
  db:
    image: postgres:11
    volumes:
      - local_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  backend:
    stdin_open: true
    tty: true
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /app
    restart: always
    volumes:
      - .:/app:delegated
    environment:
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  local_data:
  node_modules:
