# Generated by Django 3.1.1 on 2020-10-01 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(name="customuser", managers=[],),
    ]
