# Generated by Django 3.1.1 on 2020-10-02 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20201001_0403"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser", options={"verbose_name": "user"},
        ),
    ]
