# Generated by Django 3.1.1 on 2020-10-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20201002_0120"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                default="user@example.com", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
    ]
