# Generated by Django 3.1.1 on 2020-10-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20201015_2003"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Account with this email already exists"},
                max_length=254,
                unique=True,
            ),
        ),
    ]
