# Generated by Django 3.1.1 on 2020-10-07 19:02

import apps.calls.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0003_call_week_of"),
    ]

    operations = [
        migrations.AlterField(
            model_name="call",
            name="week_of",
            field=models.DateField(
                validators=[apps.calls.validators.validate_start_of_the_week]
            ),
        ),
    ]
