# Generated by Django 3.1.1 on 2020-10-07 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calls", "0004_auto_20201007_1902"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipient",
            name="user",
            field=models.ForeignKey(
                default="04e1b17e-32d8-4b52-b1dd-8979117edfe3",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipients",
                to="core.customuser",
            ),
            preserve_default=False,
        ),
    ]
