# Generated by Django 3.1.1 on 2020-10-15 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0005_recipient_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="call", name="week_of",),
        migrations.AddField(
            model_name="call",
            name="date",
            field=models.DateField(default=datetime.date(2020, 10, 15)),
            preserve_default=False,
        ),
    ]
