# Generated by Django 3.1.1 on 2020-10-19 07:41

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0006_auto_20201015_1715"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="state_residence",
            field=localflavor.us.models.USStateField(
                blank=True, max_length=2, null=True
            ),
        ),
    ]
