# Generated by Django 3.1.1 on 2020-10-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0007_auto_20201019_0741"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="political_leaning",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fl", "Far Left"),
                    ("le", "Left"),
                    ("cl", "Center Left"),
                    ("m", "Middle"),
                    ("cr", "Center Right"),
                    ("ri", "Right"),
                    ("fr", "Far Right"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="registered_to_vote",
            field=models.CharField(
                blank=True,
                choices=[("re", "Registered"), ("nr", "Not Registered")],
                max_length=2,
            ),
        ),
    ]
