// Auth actions
export const ACTION_LOGIN = "ACTION_LOGIN";
export const ACTION_LOGIN_SUCCESS = "ACTION_LOGIN_SUCCESS";
export const ACTION_LOGIN_FAIL = "ACTION_LOGIN_FAIL";
export const ACTION_LOGOUT = "ACTION_LOGOUT";

// Dashboard Actions
export const ACTION_LOAD_CALLS = "ACTION_LOAD_CALLS";
export const ACTION_LOAD_CALLS_SUCCESS = "ACTION_LOAD_CALLS_SUCCESS";
export const ACTION_LOAD_CALLS_FAIL = "ACTION_LOAD_CALLS_FAIL";
export const ACTION_LOAD_RECIPIENTS = "ACTION_LOAD_RECIPIENTS";
export const ACTION_LOAD_RECIPIENTS_SUCCESS = "ACTION_LOAD_RECIPIENTS_SUCCESS";
export const ACTION_LOAD_RECIPIENTS_FAIL = "ACTION_LOAD_RECIPIENTS_FAIL";

export const ACTION_CREATE_RECIPIENTS_SUCCESS = "ACTION_CREATE_RECIPIENTS_SUCCESS";

// Alert actions
export const ALERT_MESSAGE = 'ALERT_MESSAGE'
