// Auth actions
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS'
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS'
export const RESET_PASSWORD_CONFIRM_FAIL = 'RESET_PASSWORD_CONFIRM_FAIL'
export const LOGOUT = 'LOGOUT'
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL'
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS'
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS'
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL'

// Dashboard Actions
export const ACTION_LOAD_CALLS = 'ACTION_LOAD_CALLS'
export const ACTION_LOAD_CALLS_SUCCESS = 'ACTION_LOAD_CALLS_SUCCESS'
export const ACTION_LOAD_CALLS_FAIL = 'ACTION_LOAD_CALLS_FAIL'
export const ACTION_LOAD_RECIPIENTS = 'ACTION_LOAD_RECIPIENTS'
export const ACTION_LOAD_RECIPIENTS_SUCCESS = 'ACTION_LOAD_RECIPIENTS_SUCCESS'
export const ACTION_LOAD_RECIPIENTS_FAIL = 'ACTION_LOAD_RECIPIENTS_FAIL'

export const ACTION_CREATE_RECIPIENTS_SUCCESS =
  'ACTION_CREATE_RECIPIENTS_SUCCESS'
export const ACTION_USER_UPDATE_SUCCESS = 'ACTION_USER_UPDATE_SUCCESS'

// Alert actions
export const ALERT_MESSAGE = 'ALERT_MESSAGE'
