// Auth actions
export const ACTION_LOGIN = "ACTION_LOGIN";
export const ACTION_LOGIN_SUCCESS = "ACTION_LOGIN_SUCCESS";
export const ACTION_LOGIN_FAIL = "ACTION_LOGIN_FAIL";
export const ACTION_LOGOUT = "ACTION_LOGOUT";
